Models/Cart.cs
using System;
using System.Collections.Generic;

namespace Assignment_2_NEW.Models;

public partial class Cart
{
    public int CartId { get; set; }

    // public string CustomerId { get; set; } = null!;

    public string ProductId { get; set; } = null!;

    public int Quantity { get; set; }

    // public string? CartDetail { get; set; }

    // public DateTime? OrderCreation { get; set; }

    public virtual Product Product { get; set; } = null!;
}

Controllers/CartsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Assignment_2_NEW.Models;
using Newtonsoft.Json.Schema;

namespace Assignment_2_NEW.Controllers
{
    public class CartsController : Controller
    {
        // GET: Carts
        public IActionResult Index()
        {
            var CartCurrent = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "CartCurrent");
            ViewBag.CartCurrent = CartCurrent;
            if (HttpContext.Session.GetInt32("CurrentSession") == 606)
            {
                if (CartCurrent != null)
                {
                    ViewBag.Total = CartCurrent.Sum(Itm => Itm.Product?.Price * Itm.Quantity);
                }
                return View();
            }
            else
            {
                return RedirectToAction("Customer", "Login");
            }
        }

        public IActionResult Buy(string ItemID)
        {
            ProductList2Cart Getter = new ProductList2Cart();
            if (SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "CartCurrent") == null)
            {
                List<Item> CartCurrent = new List<Item>();
                CartCurrent.Add(new Item { Product = Getter.Find(ItemID), Quantity = 1 });

                SessionHelper.SetObjectAsJson(HttpContext.Session, "CartCurrent", CartCurrent);
            }
            else
            {
                List<Item>? CartCurrent = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "CartCurrent");
                int FindIndex = Coexists(ItemID);
                if (FindIndex != -1)
                {
                    if (CartCurrent != null)
                    {
                        CartCurrent[FindIndex].Quantity++;
                    }
                }
                else
                {
                    if (CartCurrent != null)
                    {
                        CartCurrent.Add(new Item { Product = Getter.Find(ItemID), Quantity = 1 });
                    }
                }
                if (CartCurrent != null)
                {
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "CartCurrent", CartCurrent);
                }
            }
            if (HttpContext.Session.GetInt32("CurrentSession") == 606)
            {
                return RedirectToAction("Index", "Carts");
            }
            else
            {
                return RedirectToAction("Customer", "Login");
            }
        }

        public IActionResult DeleteItem(string ItemID)
        {
            List<Item>? CartCurrent = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "CartCurrent");
            int ListIndex = Coexists(ItemID);
            if (CartCurrent != null)
            {
                CartCurrent.RemoveAt(ListIndex);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "CartCurrent", CartCurrent);
            }
            if (HttpContext.Session.GetInt32("CurrentSession") == 606)
            {
                return RedirectToAction("Index", "Carts");
            }
            else
            {
                return RedirectToAction("Customer", "Login");
            }
        }

        private int Coexists(string ItemID)
        {
            List<Item>? CartCurrent = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "CartCurrent");
            if (CartCurrent != null)
            {
                for (int Index = 0; Index < CartCurrent.Count; Index++)
                {

#pragma warning disable CS8602 // Dereference of a possibly null reference.
                    if (CartCurrent[Index].Product.ProductId == ItemID)
                    {
                        return Index;
                    }
#pragma warning restore CS8602 // Dereference of a possibly null reference.
                }
            }
                return -1;
        }
    }
}

Controllers/ProductListController.cs
using Assignment_2_NEW.Models;
using Microsoft.AspNetCore.Mvc;

namespace Assignment_2_NEW.Controllers
{
    public class ProductListController : Controller
    {
        private readonly AssignmentDatabaseContext _Context;

        public ProductListController(AssignmentDatabaseContext Context)
        {
            _Context = Context;
        }
        public IActionResult Index()
        {
            ProductList2Cart Getter = new ProductList2Cart();
            ViewBag.Products = Getter.FindAll();
            if (HttpContext.Session.GetInt32("CurrentSession") == 606)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Customer", "Login");
            }
        }
    }
}

Views/Carts/Index.cshtml
@{
    ViewData["Title"] = "Giỏ hàng của bạn";
}
@{
    var _Item = ViewBag.CartCurrent as List<Item>;
}
<h1>Giỏ hàng của bạn</h1>
<div class="row">
    <table class="table table-hover table-bordered">
        <thead class="bg-info bg-opacity-25 border-primary font-weight-bold">
            <tr>
                <td class="b">Lựa chọn</td>
                <td>ID mặt hàng</td>
                <td>Tên</td>
                <td>Giá</td>
                <td>Số lượng</td>
                <td>Tổng chi</td>
            </tr>
        </thead>
        <tbody>
            @if (_Item != null)
            {
                @foreach (var item in _Item)
                {
                    if (item != null && item.Product != null)
                    {
                        <tr>
                            <td>
                                <a class="btn btn-danger" asp-controller="Carts" asp-action="DeleteItem" asp-route-ItemID="@item.Product.ProductId">Loại bỏ</a>
                            </td>
                            <td>
                                @item.Product.ProductId
                            </td>
                            <td>@item.Product.ProductName</td>
                            <td>@item.Product.Price</td>
                            <td>@item.Quantity</td>
                            <td>@(item.Product.Price * item.Quantity)</td>
                        </tr>
                    }
                }

            }
        </tbody>
        <tfoot class="font-weight-bold">
            <tr>
                <td colspan="5" style=" text-align: right;">Tổng chi tất cả</td>
                <td>@ViewBag.Total</td>
            </tr>
        </tfoot>
    </table>
</div>
<div class="row">
    <a class="btn btn-success" asp-controller="ProductList" asp-action="Index">Tiếp tục mua hàng</a>
</div>
